### ISSUE TITLE
server crashed!

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [Yuria-Shikibe/NewHorizonMod#27]
[07-18-2021 14:30:32] [E] java.lang.NoSuchFieldError: updateEffect
        at newhorizon.content.NHBlocks$1.<init>(NHBlocks.java:127)
        at newhorizon.content.NHBlocks.loadEnv(NHBlocks.java:119)
        at newhorizon.content.NHBlocks.load(NHBlocks.java:1814)
        at newhorizon.NewHorizon.loadContent(NewHorizon.java:181)
        at mindustry.mod.Mods.loadContent(Mods.java:580)
        at mindustry.core.ContentLoader.createModContent(ContentLoader.java:74)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:50)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:65)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:53)

**Comment by Yuria-Shikibe** [comment]
我知道，，我正在适配128.1
