### ISSUE TITLE
Crash on winning a sector

### ISSUE THREAD

**Issue by Benni204** [Yuria-Shikibe/NewHorizonMod#35]
Game crashes on multiple maps during Sector completion.
If it crashes once, it crashs everytime u join back that sector.

Mindustry has crashed. How unfortunate.
Version: steam build 130.1
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
1 Mods: new-horizon:1.9.7 Beta

java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
	at arc.struct.ObjectMap.containsKey(ObjectMap.java:497)
	at newhorizon.content.NHSectorPresets.lambda$load$0(NHSectorPresets.java:80)
	at arc.Events.lambda$fire$2(Events.java:31)
	at arc.struct.Seq.each(Seq.java:200)
	at arc.Events.fire(Events.java:31)
	at arc.Events.fire(Events.java:26)
	at mindustry.core.Logic.sectorCapture(Logic.java:282)
	at mindustry.gen.Call.sectorCapture(Call.java:752)
	at mindustry.core.Logic.checkGameState(Logic.java:231)
	at mindustry.core.Logic.update(Logic.java:414)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:174)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:166)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:154)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by 3Snake3** [comment]
The same situation is on android
